version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/data/postgres:/var/lib/postgresql/data # Updated to a user's home directory
    env_file:
      - docker.env
    networks:
      - postgres

  pgadmin:
    links:
      - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - ~/data/pgadmin:/root/.pgadmin # Updated to a user's home directory
    env_file:
      - docker.env
    networks:
      - postgres

  nodeapp:
    container_name: backend
    build: .
    volumes:
      - .:/usr/app/
    ports:
      - "5001:5001"
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - postgres
    env_file:
      -  .env
    networks:
      - postgres

networks:
  postgres:
    driver: bridge
